"use client";
import { useEffect, useState } from 'react';
import type { productionHealth } from '@/worker/production';
type Health=Awaited<ReturnType<typeof productionHealth>>;
const pct=(n:number)=>`${(n*100).toFixed(2)} %`;
export function ProductionStatus(){
  const [data,setData]=useState<Health|null>(null),[error,setError]=useState(false);
  useEffect(()=>{let alive=true;const load=async()=>{try{const r=await fetch('/api/production',{cache:'no-store'});if(!r.ok)throw new Error();const body=await r.json();if(alive){setData(body);setError(false);}}catch{if(alive)setError(true);}};void load();const timer=setInterval(load,60000);return()=>{alive=false;clearInterval(timer);};},[]);
  return <section className="lab-panel production-status" aria-label="Evidence und Hintergrundbetrieb">
    <h2>Evidence & Hintergrundbetrieb</h2>
    {error?<p role="status">Status derzeit nicht erreichbar. Letzte Anzeige kann veraltet sein.</p>:!data?<p>Lade gespeicherten Betriebsstand …</p>:null}
    {data&&<>
      <p><strong>Datenquellen: {data.dataSourceStatus?.replaceAll('-',' ').toUpperCase()??'UNAVAILABLE'}</strong> · PARTIAL LIVE beschreibt ausschließlich die Datenabdeckung, nicht den Lernstatus.</p>
      <p>ML: <strong>{data.mlStatus}</strong> · ML {pct(data.mlInfluence)} · Hypothesen {pct(data.hypothesisInfluence)} · adaptiv gesamt {pct(data.adaptiveTotalInfluence)} · gemeinsamer Deckel {pct(data.adaptiveCap)}</p>
      <p>Automatische Freigabe: {data.runtimeGateStatus} · Evidence: {data.evidencePipelineStatus}</p>
      <p>Runtime: {Object.entries(data.runtimeFlags??{}).map(([name,enabled])=>`${name}=${enabled}`).join(' · ')}</p>
      <p>{data.snapshotCount} Snapshots · {data.trainingExamples} abgeschlossene ML-Beispiele · {data.resolvedOutcomes} Ergebnisse · {data.activeHypotheses}/{data.hypothesisCount} Hypothesen aktiv</p>
      <details><summary>Validation je Horizon: Daten, Abhängigkeit und nächste Bedingung</summary>
        <p>Ein Forecast-Datum zählt als ein Zeitcluster. Überlappende Labels bleiben erhalten. ESS ist die geschätzte effektive Information nach HAC; sie ist keine Trefferquote. Mindestinformation, echte zukünftige Shadow-Ergebnisse und Multiple Testing bleiben Pflicht.</p>
        <div className="lab-scroll"><table><thead><tr><th>Horizon / Zweck</th><th>Raw / Daten / Overlap</th><th>Training / ESS</th><th>WF / OOS / Purging</th><th>Holdout / Shadow</th><th>Nächste Bedingung</th></tr></thead><tbody>{(data.validation??[]).map(v=><tr key={v.horizon}><td>{v.horizon}D<div>{v.purpose}</div></td><td>{v.rawObservations} / {v.uniqueForecastDates}<div>überlappende Intervallpaare: {pct(v.overlappingLabelRatio)}</div></td><td>{v.trainingExamples} / {v.oosSamples?v.effectiveSampleSize.toFixed(1):'noch keine OOS-ESS'}</td><td>{v.folds} Folds / {v.oosSamples} OOS / {v.purgedRows} entfernt</td><td>{v.holdoutStatus}<div>{v.shadowStatus} · ESS {v.shadowEffectiveSampleSize.toFixed(1)}</div></td><td>{v.blocker}</td></tr>)}</tbody></table></div>
        <p>Die Label-Prozess-ESS beschreibt nur die Outcome-Reihe. Die Freigabe benutzt die ESS der gepaarten Loss-Verbesserung des jeweiligen eingefrorenen Kandidaten. 1D / 3D / 5D ersetzen kein langes Label.</p>
      </details>
      <p>Letzter Snapshot: {data.lastSuccessfulSnapshot??'Noch keiner'} · Retraining: {data.lastRetrain??'WAITING FOR DATA'}</p>
      <p>Letzter erfolgreicher regulärer Cron: {data.lastSuccessfulRealCronRefresh?.completedAt??'WAITING FOR NEXT SCHEDULED RUN'} · letzter erfolgreicher Daily Refresh: {data.lastSuccessfulDailyRefresh?.completedAt??'WAITING'}.</p>
      <p>Weekly Cron: {data.lastRegularWeeklyRetrain?.status??'WAITING FOR NEXT SCHEDULED RUN'} · vollständig belegte Core-Faktoren aktuell: {data.coverage?.fresh??0}/{data.coverage?.factors??80} · {data.observationCount} aktuelle Beobachtungen.</p>
      <p>Core Coverage: <strong>{data.coverage.fresh}/{data.coverage.factors}</strong> · Critical Coverage: <strong>{data.coverage.critical?.fresh??0}/{data.coverage.critical?.total??0} ({pct(data.coverage.critical?.ratio??0)})</strong></p>
      <p>CARRIED INPUT: {data.coverage.carried} · PARTIAL: {data.coverage.partial} · STALE: {data.coverage.stale??0} · Faktoren mit Quellfehler: {data.coverage.failed??0} · ohne belegte Eingaben: {data.coverage.unavailable??0}. Die Qualitätsmerkmale können sich überschneiden.</p>
      <p>Research Coverage: {data.researchCoverage.connected}/{data.researchCoverage.families} angebundene Datenfamilien mit gültigen Eingaben · {data.researchCoverage.freshObservations} aktuelle Research-Beobachtungen. Diese Abdeckung entscheidet nicht über Core LIVE.</p>
      <details><summary>Coverage-Regeln und offene Abhängigkeiten</summary>
        <p>FULL LIVE: alle 80 Core-Faktoren vollständig und aktuell belegt. LIVE: sämtliche kritischen Abhängigkeiten belegt, jede Core-Kategorie vertreten; einzelne schwache Kontextfaktoren dürfen fehlen. PARTIAL LIVE: kritische Lücke oder vollständig fehlende Kategorie. BASELINE: keine ausreichenden aktuellen Quellenbelege.</p>
        <p>Fehlende kritische Abhängigkeiten: {data.coverage.critical?.missing.join(', ')||'keine'}. Vollständig fehlende Kategorien: {data.coverage.categoryGaps?.join(', ')||'keine'}.</p>
        <div className="lab-scroll"><table><thead><tr><th>Währung / Faktor</th><th>Kritikalität</th><th>Begründung</th><th>Freshness</th></tr></thead><tbody>{data.coreRequirements.map(r=><tr key={r.currency+r.factor}><td>{r.currency} / {r.factor}</td><td>{r.critical?'KRITISCH':'KONTEXT'} · {pct(r.weight)}</td><td>{r.reason}</td><td>{r.freshness}</td></tr>)}</tbody></table></div>
      </details>
      <details><summary>Research-Quellen und Herkunft</summary><p>Beobachtbare Features sind keine bestätigten FX-Signale. Rohstoffe, Kriminalstatistik und Shipping durchlaufen dieselben Prospective-, OOS- und Redundanz-Gates. Jeder Punkt in der Punktewolke bleibt ein vollständiger Währungsmodellzustand.</p>
        <div className="lab-scroll"><table><thead><tr><th>Datenfamilie</th><th>Status</th><th>Features</th><th>Währungen</th><th>Letzte Periode</th></tr></thead><tbody>{data.researchCoverage.classes.map(r=><tr key={r.name}><td>{r.name}</td><td>{r.status}</td><td>{r.features}</td><td>{r.currencies.join(', ')||'—'}</td><td>{r.latestPeriod??'—'}</td></tr>)}</tbody></table></div>
      </details>
      <details><summary>Core, Beiträge und Verlauf</summary>
        {data.evidenceHistory.length?data.evidenceHistory.slice(0,10).map((row:{asOf:string;attributions:Record<string,{coreEvidenceScore:number;mlContribution:number;hypothesisContribution:number;finalEvidenceScore:number;modelVersion:string|null;components:unknown[]}>})=><details key={row.asOf}><summary>{row.asOf}</summary><div className="lab-scroll"><table><thead><tr><th>Währung</th><th>Core</th><th>ML</th><th>Hypothesen</th><th>Final</th></tr></thead><tbody>{Object.entries(row.attributions).map(([c,a])=><tr key={c}><th>{c}</th><td>{a.coreEvidenceScore.toFixed(4)}</td><td>{a.mlContribution.toFixed(4)}</td><td>{a.hypothesisContribution.toFixed(4)}</td><td>{a.finalEvidenceScore.toFixed(4)}</td></tr>)}</tbody></table></div></details>):<p>Der nächste erfolgreiche Refresh beginnt die neue, nachvollziehbare Historie.</p>}
      </details>
      <details><summary>Hypothesen, Modelle und Datenqualität</summary>
        <p>Freigabe erfolgt automatisch nach zeitlich getrennter Prüfung und neuen Shadow-Ergebnissen. Unbelegte Signale tragen 0 bei. Score-Werte sind keine gemessenen Trefferquoten.</p>
        <p>Aktuelles Modell: {data.currentMlVersion} · Rollbacks: {data.rollbackCount}</p>
        <p>{data.observationVintages} unveränderliche Datenstände. Jahresdaten ändern sich erst bei einer Veröffentlichung oder Revision. Fortgeführte Faktoren bleiben als solche gekennzeichnet und qualifizieren keine neue adaptive Freigabe.</p>
        {data.coreInputQuality&&<details><summary>Herkunft der Core-Faktoren</summary><p>FRESH heißt innerhalb des Aktualitätsfensters, nicht heute veröffentlicht oder live gehandelt. PARTIAL enthält fortgeführte Teilwerte; die Coverage ist keine Live-Feed-Quote. BIS-Daten: Quelle Bank for International Settlements; deutsche Erläuterungen sind keine offizielle BIS-Übersetzung.</p><div className="lab-scroll"><table><thead><tr><th>Währung</th><th>Faktor</th><th>Status</th><th>Periode</th><th>Quelle</th></tr></thead><tbody>{Object.entries(data.coreInputQuality as Record<string,Record<string,{status:string;availability?:string;period:string|null;source:string;sourceUrls?:string[];failure?:string|null}>>).flatMap(([currency,factors])=>Object.entries(factors).map(([factor,q])=><tr key={currency+factor}><td>{currency}</td><td>{factor}</td><td>{q.availability??q.status}{q.status.startsWith('PARTIAL')?' · PARTIAL':''}{q.failure&&<div>{q.failure}</div>}</td><td>{q.period??'nicht belegt'}</td><td>{q.source}{q.sourceUrls?.map(url=><div key={url}><a href={url} target="_blank" rel="noreferrer">Quelle öffnen</a></div>)}</td></tr>))}</tbody></table></div></details>}
        <p>{Object.entries(data.hypothesisLifecycle??{}).map(([status,count])=>`${status}: ${count}`).join(' · ')} · Kontext-ML: {data.contextLearning?.status??'WAITING FOR DATA'}.</p>
        {data.contextLearning.models.length>0&&<details><summary>Context-ML nach Currency / Pair und Horizon</summary>{data.contextLearning.models.map(m=><p key={m.id}>{m.scope} · {m.horizon}D · {m.status} · Training {m.samples} · historische ESS {m.historicalGate?.diagnostics?.effectiveSampleSize.toFixed(1)??'—'} · Holdout {m.holdoutGate?.reason??'WAITING'} · Ensemble-Vergleich {m.historicalIncrementalGate?.reason??'WAITING'} / {m.holdoutIncrementalGate?.reason??'WAITING'} · Shadow {m.gate.reason} · Folds {m.folds} / entfernt {m.purgedRows}</p>)}</details>}
        <p>Jahres- und Monatsdaten besitzen eigene Aktualitätsfenster. Ein LIVE-Label erhöht weder Modellvertrauen noch ML-Einfluss. Nur vollständig belegte Core-Faktoren erhalten FRESH.</p>
        <details><summary>Zusätzliche Shadow-Targets</summary><p>Anfangs unkalibrierte Kandidaten, keine gemessenen Wahrscheinlichkeiten; kein Richtungseinfluss.</p>{data.eventTargets?.map(t=><p key={t.target+t.horizon}>{t.target} · {t.horizon}D · {t.status} · {t.resolved} Outcomes · Einfluss 0. {t.definition}</p>)}</details>
        <details><summary>Noch nicht angebundene Datenklassen</summary>{data.notConnected?.map(s=><p key={s.name}><strong>{s.name} · {s.status}</strong> ({s.scope}): {s.reason}{'history' in s&&<span> Historie: {s.history}. Frequenz: {s.frequency}. Point-in-Time: {s.pointInTime}. Integration: {s.integration}.</span>}</p>)}</details>
        {data.lastError&&<p role="status">Letzter Fehler: {data.lastError}</p>}
        {data.failedDataSources.map((s:{source:string;currency:string;cause:string;fallback:string},i:number)=><p key={`${s.source}-${i}`}>{s.source} / {s.currency}: {s.cause==='PREMIUM_REQUIRED'?'PREMIUM SOURCE RECOMMENDED':'FAILED / UNAVAILABLE'} · {s.cause}. {s.fallback}</p>)}
        {data.registry.map(r=><details key={r.id}><summary>{r.feature} · {r.operator} · {r.horizon}D · {r.status}</summary><p>{r.reason}</p><p>Version {r.version} · Gewicht {pct(r.weight)} · effektive Information {r.gate?.diagnostics?.effectiveSampleSize.toFixed(1)??'noch keine Validation'}</p>{!r.progress&&<p>Detaildiagnose folgt mit dem nächsten Daily Refresh.</p>}<p>Historisch: {r.progress?.historical.rawObservations??'—'} Raw · {r.progress?.historical.uniqueForecastDates??'—'} Forecast-Daten · ESS {r.progress?.historical.effectiveSampleSize.toFixed(1)??'—'} · Overlap {pct(r.progress?.historical.overlappingLabelRatio??0)}</p><p>Holdout: {r.progress?.holdoutStatus??'NOT YET TESTED'} · Shadow: {r.progress?.shadow.rawObservations??'—'} Raw / {r.progress?.shadow.uniqueForecastDates??'—'} Daten / ESS {r.progress?.shadow.effectiveSampleSize.toFixed(1)??'—'}</p><p>Regimes: {Object.entries(r.gate?.regimeFit??{}).map(([name,fit])=>`${name}: ${fit?'belegt':'unzureichend'}`).join(' · ')||'WAITING FOR DATA'} · nächste Bedingung: {r.progress?.nextCondition??r.reason}</p><p>{r.rationale}</p><p>{r.id}</p></details>)}
      </details>
    </>}
  </section>;
}
