import { observationQuality, type Observation, type SourceCheck } from './production-data';

export const sourceGaps=[
  {name:'CAD Commodity Core',scope:'CORE',status:'UNAVAILABLE',reason:'Free official BoC BCPI has documented Canadian production weights. The existing Core has no index-to-factor definition; buying prices cannot supply that missing model definition. No arbitrary oil-only replacement.'},
  {name:'AUD Commodity Core',scope:'CORE',status:'UNAVAILABLE',reason:'RBA export-weighted commodity baskets are already Research inputs. Their official export weights do not define an FX sign, lag or normalized Core score. No automatic Research-to-Core promotion.'},
  {name:'NZD Commodity Core',scope:'CORE',status:'UNAVAILABLE',reason:'Stats NZ quarterly export-price/terms-of-trade indexes include dairy and food with official methodology. The existing normalized Commodity Core mapping is undefined; no invented dairy weights or daily freshness.'},
  {name:'JPY Commodity Core',scope:'CORE',status:'UNAVAILABLE',reason:'BoJ monthly import-price energy components have official weights and yen/contract-currency variants. Selecting FX-neutral exposure and mapping to the Core needs an explicit model definition; oil is not a complete import basket.'},
  {name:'GBP 2Y nominal sovereign yield',scope:'CORE',status:'PREMIUM SOURCE RECOMMENDED',reason:'BoE IUDMNPY 10Y nominal par CSV is connected separately; this does not certify the pair. Audited BoE full curves contain spot/forward rates, while DMO averages are monthly and start at 5Y. No equivalent daily 2Y public input was verified; paid data is a recommendation, not proof that no free source exists.',history:'At least 5 years, including benchmark rolls',frequency:'business-daily closing observations',pointInTime:'Actual quote/receipt times, nominal coupon-equivalent yield convention, maturity and revision vintages',integration:'Verify a compatible 2Y input or a consistently defined 2Y/10Y pair; no spot-to-par substitution'},
  {name:'CHF 2Y + 10Y nominal sovereign yields',scope:'CORE',status:'PREMIUM SOURCE RECOMMENDED',reason:'SNB public Confederation curves are zero-coupon spot rates; OECD/FRED long rates are monthly and lack the 2Y leg. A compatible daily nominal pair was not verified for the existing Core.',history:'At least 5 years across rate regimes',frequency:'business-daily synchronized pair',pointInTime:'CHF Confederation issuer, exact maturity/yield convention, quotation timestamps and corrections',integration:'Licensed or equivalently reliable free paired adapter; never corporate, swap, policy or zero-coupon replacements'},
  {name:'NZD 2Y + 10Y nominal sovereign yields',scope:'CORE',status:'NOT YET CONNECTED',reason:'RBNZ B2 officially supplies daily secondary-market government closing yields for both maturities, including history. The public XLSX download returned HTTP 403 in this audit. Access is blocked, not a proven premium-data requirement; no bypass or synthetic substitute.'},
  {name:'Risk anchor',scope:'CORE',status:'CARRIED INPUT',reason:'The existing risk formula retains a fixed 50% anchor. Macro receipts cannot certify that anchor. Preserved to avoid an unrequested Core change.'},
  {name:'JPY / NZD central-bank language',scope:'CORE',status:'NOT YET CONNECTED',reason:'JPY RSS offers dated headlines, not sufficient speech text; NZ endpoint access is unavailable. No artificial neutral sentiment.'},
  {name:'FX options / IV / risk reversals / skew',scope:'RESEARCH',status:'PREMIUM SOURCE RECOMMENDED',reason:'Need licensed consistent currency-pair volatility surfaces, delta conventions and timestamps; realized FX volatility is not implied volatility.',history:'5–10 years across stress regimes',frequency:'daily, fixed fixing',pointInTime:'As-quoted surfaces, tenor/delta definitions and vendor corrections',integration:'Versioned pair/tenor/delta adapter; separate event-target calibration; no directional default'},
  {name:'Cross-currency basis / implied rate paths',scope:'RESEARCH',status:'PREMIUM SOURCE RECOMMENDED',reason:'Funding indices and policy rates cannot reproduce executable basis or market-implied OIS paths.',history:'5–10 years',frequency:'daily synchronized curve snapshots',pointInTime:'As-of quotes, tenor and collateral conventions, corrected quote vintages',integration:'Pair-specific basis and OIS curve adapters; preserve observation and receipt times'},
  {name:'Freight spot prices / port and vessel activity',scope:'RESEARCH',status:'PREMIUM SOURCE RECOMMENDED',reason:'GSCPI and annual container throughput are partial proxies, not container spot rates or a real-time global port panel.',history:'At least 5 years',frequency:'daily/weekly',pointInTime:'As-published route/container definitions; vessel aggregation and revisions',integration:'Licensed aggregate route/port panel; currency trade exposure; no vessel/person tracking UI'},
  {name:'Forecast / expectation dispersion',scope:'RESEARCH',status:'PREMIUM SOURCE RECOMMENDED',reason:'Requires timestamped independent forecast vintages; model point-cloud dispersion is not economist disagreement.',history:'5 years of individual forecast vintages',frequency:'each forecast release',pointInTime:'Pre-release consensus, contributor changes and exact cutoff',integration:'Dispersion from frozen survey panels; no revised-history backfill'},
  {name:'Daily grain futures / crop-region weather',scope:'RESEARCH',status:'NOT YET CONNECTED',reason:'Connected grain prices are monthly IMF benchmarks; NOAA weather is monthly CONUS. No licensed daily futures, intraday heat stress or crop-weighted weather panel is claimed.'},
  {name:'WASDE / crush / agricultural forecast surprises',scope:'RESEARCH',status:'NOT YET CONNECTED',reason:'USDA NASS and inspection releases are separate from WASDE balance sheets, soybean crush and a timestamped pre-release consensus. No fabricated surprise or composite weights.'},
  ...['Google Trends','Social media','YouTube activity','Retail positioning','Broad news acceleration / novelty'].map(name=>({name,scope:'RESEARCH',status:'NOT YET CONNECTED',reason:'No configured stable authorized point-in-time feed. Existing official central-bank narratives remain separately available.'})),
];
const families=[
  {name:'Positioning change / acceleration',prefixes:['alt.cot.']},
  {name:'Energy spot-price proxies',prefixes:['alt.global.energy.']},
  {name:'Funding / financial conditions',prefixes:['alt.global.funding.']},
  {name:'Labor / consumption',prefixes:['alt.us.labor.','alt.us.consumption.']},
  {name:'Official central-bank narratives',prefixes:['alt.narrative.']},
  {name:'Sovereign yield curve / repricing',prefixes:['alt.rates.']},
  {name:'Australian commodity export baskets',prefixes:['alt.commodity.basket.']},
  {name:'Supply chains / aggregate port volumes',prefixes:['alt.global.supply.','alt.supply.']},
  {name:'Aggregate public-safety statistics',prefixes:['alt.safety.']},
  {name:'Electricity / real activity',prefixes:['alt.activity.']},
  {name:'Metadata-discovered economic proxies',prefixes:['alt.proxy.','proxy.']},
  {name:'Agricultural monthly price proxies',prefixes:['alt.agri.price.']},
  {name:'US crop progress / condition / moisture',prefixes:['alt.agri.crop.']},
  {name:'US agricultural estimates / acreage / stocks',prefixes:['alt.agri.estimate.','alt.agri.acreage.','alt.agri.stocks.']},
  {name:'US drought / monthly weather',prefixes:['alt.agri.drought.','alt.agri.weather.']},
  {name:'US ethanol production / inventories',prefixes:['alt.agri.ethanol.']},
  {name:'US grain export inspections',prefixes:['alt.agri.exports.']},
];
export type ResearchReceipt=Pick<Observation,'currency'|'metric'|'value'|'period'|'receivedAt'|'releaseDate'|'source'|'sourceUrl'|'quality'|'frequency'|'featureVersion'|'publicationDate'|'scheduledPublicationAt'|'researchExposures'>;
export function researchCoverage(observations:ResearchReceipt[],checks:SourceCheck[],at:string){
  const latest=new Map<string,ResearchReceipt>();
  for(const o of observations.filter(o=>o.metric.startsWith('alt.')||o.metric.startsWith('proxy.'))){const id=o.currency+':'+o.metric,old=latest.get(id);if(!old||old.receivedAt<o.receivedAt)latest.set(id,o);}
  const receipts:ResearchReceipt[]=[...latest.values()].map(({currency,metric,value,period,receivedAt,releaseDate,source,sourceUrl,quality,frequency,featureVersion,publicationDate,scheduledPublicationAt,researchExposures})=>({currency,metric,value,period,receivedAt,releaseDate,source,sourceUrl,quality,frequency,featureVersion,...(publicationDate!==undefined?{publicationDate}:{}),...(scheduledPublicationAt?{scheduledPublicationAt}:{}),...(researchExposures?{researchExposures}:{})}));
  const current=(r:ResearchReceipt)=>Number.isFinite(Date.parse(r.receivedAt))&&r.receivedAt<=at&&(!r.releaseDate||Number.isFinite(Date.parse(r.releaseDate))&&r.releaseDate<=at)&&(!r.publicationDate||r.publicationDate<=at.slice(0,10))&&(!r.scheduledPublicationAt||r.scheduledPublicationAt<=at)&&r.quality==='VALID'&&observationQuality(r.metric,r.value,r.period,at)==='VALID';
  const classes=families.map(f=>{const rows=receipts.filter(r=>f.prefixes.some(p=>r.metric.startsWith(p))),fresh=rows.filter(current),failed=checks.some(c=>c.status!=='SUCCESS'&&c.metrics.some(m=>f.prefixes.some(p=>m.startsWith(p))));
    return {name:f.name,status:fresh.length?(failed||fresh.length<rows.length?'PARTIAL':'FRESH'):rows.length?'STALE':failed?'FAILED':'WAITING FOR DATA',features:new Set(fresh.map(r=>r.metric)).size,observations:fresh.length,currencies:[...new Set(fresh.flatMap(r=>r.researchExposures?.map(e=>e.currency)??[r.currency]))],latestPeriod:rows.map(r=>r.period).sort().at(-1)??null,sourceUrls:[...new Set(rows.map(r=>r.sourceUrl))]};});
  return {asOf:at,scope:'Available registered Research families; independent of Core LIVE and adaptive qualification. Not a percentage of all possible alternative data.',families:classes.length,connected:classes.filter(c=>c.observations>0).length,freshObservations:receipts.filter(current).length,classes,receipts,notConnected:sourceGaps.filter(g=>g.scope==='RESEARCH')};
}
